language: java
branches:
  only:
  - master

jdk:
- openjdk10

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jobs:
  include:
  - name: deploy javadoc
    stage: deploy
    if: branch = master
    script: "gradle javadoc"
    deploy:
      provider: pages
      github-token: $GITHUB_TOKEN
      skip-cleanup: true
      local-dir: build/docs/javadoc
